server:
  port: 8088

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diniuwang?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    mvc:
      pathmatch:
        matching-strategy=ANT_PATH_MATCHER

  #redis
  redis:
    host: redis
    port: 6379
    database: 0

#spring boot集成mybatis的方式打印sql
logging:
  level:
    com.gxweilan.DiNiuWang.mapper: DEBUG

#mybatis.mapper 文件的扫描路径
mybatis:
  #指定log-spring.xml日志配置文件的路径
  logging.config=classpath:log/logback-spring.xml
  logging.path=.
  mapper-locations=classpath*:com.gxweilan.DiNiuWang.mapper/*.xml
configuration:
  map-underscore-to-camel-case=true:
type-aliases-package=com:
  gxweilan:
    DiNiuWang:
        mybatis:
          entity:

wxpay:
  # 微信支付相关参数
  # 商户号
  mch-id: 1638345766
  # 商户API证书序列号
  mch-serial-no: 279336D952533A6462B294E239746246C454E052
  # 商户私钥文件
  private-key-path: E:\GXweilan\柳州公安\20230214狄牛网系统\zsKeyFilePath
  # APIv3密钥
  api-v3-key: diniuwang20230220akgdsengalsegeg
  # APPID
  appid: wxf574f969039228e0
  secret: eaac2f3dae82753885fae7ca3ce763d5  #小程序密钥
  # 微信服务器地址
  domain: https://api.weixin.qq.com
  # 接收结果通知地址
  # 注意：每次重新启动ngrok，都需要根据实际情况修改这个配置
  #  notify-domain:
  # APIv2密钥
  partnerKey:

  templateId: LPZzCgISs9S388u5uUyH_jFoYXCv-RTvKJskL9UVxHo  #订阅消息模板

  openid: ojTGU5L030X0Xe15ngC8n-3TVXto

#  odMxy5UTLRje--k7hXerXcL9-wkU

#druid配置
initialSize: 5
minIdle: 5
maxActive: 20
maxWait: 60000
timeBetweenEvictionRunsMillis: 60000
minEvictableIdleTimeMillis: 300000
validationQuery: SELECT 1 FROM DUAL
testWhileIdle: true
testOnBorrow: false
testOnReturn: false
poolPreparedStatements: true
usePingMethod: false

#log4j配置
filters: stat,wall,log4j
maxPoolPreparedStatementPerConnectionSize: 20
useGlobalDataSourceStat: true
connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


